### ISSUE TITLE
Database Creation/Updation Files

### ISSUE THREAD

**Issue by nyanSpruk** [nyanSpruk/PRPO-Naloge#15]
Watcher @bl4ko 
Assignee @nyanSpruk 
For each version of the project (ex. 1.0.0, 2.0.0, 2.1.0...), we should have a separate folder the database SQL files.
This is because with this, we will have a history of database structure and its modification. It will allow us to easily update database on production, testing... any branch.. without any complications.

Instead of having the SQL code in our java code, or just using it one time and forgetting what SQL we used. We will store it in files

The format should be XXX_name.sql, where XXX is the id of the file (in this current folder), so in case we need to execute files in order, we will know how.

So for example this would be the structure:
```sql
C:\USERS\NIKJANS\hello-world\POSTGRES
├───1.0.0
├───2.0.0
│       001_filename.sql
│
└───2.1.0
```

**Comment by bl4ko** [comment]
Good idea.
