### ISSUE TITLE
Zagon vsebnika s podatkovno bazo in kreiranje tabel [2 točki]

### ISSUE THREAD

**Issue by nyanSpruk** [nyanSpruk/PRPO-Naloge#8]
Since the DB's are on own computer, we have to each make our own DB

@nyanSpruk 
- [x] Zaženite vsebnik Docker s podatkovno bazo z ukazom: docker run -d --name postgres-jdbc -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=uporabniki -p 5432:5432 postgres:13

- [x] Uporabite poljubno orodje za delo z bazami PostgreSQL (npr.pgAdmin ali IntelliJ) ter ustvarite podatkovno tabelo uporabnik, ki naj vsebuje osnovne podatke o uporabniku (ime, priimek, uporabniško ime).

- [x] V bazo dodajte eno entiteto, ki jo bomo kasneje uporabili za testiranje.

@bl4ko 
- [x] Zaženite vsebnik Docker s podatkovno bazo z ukazom: docker run -d --name postgres-jdbc -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=uporabniki -p 5432:5432 postgres:13

- [x] Uporabite poljubno orodje za delo z bazami PostgreSQL (npr.pgAdmin ali IntelliJ) ter ustvarite podatkovno tabelo uporabnik, ki naj vsebuje osnovne podatke o uporabniku (ime, priimek, uporabniško ime).

- [x] V bazo dodajte eno entiteto, ki jo bomo kasneje uporabili za testiranje.

**Comment by bl4ko** [comment]
Trenutno postavitel testiral lokalno (vse deluje):
```sql
CREATE TABLE public.uporabnik (
	id serial NOT NULL,
	ime varchar NULL,
	priimek varchar NULL,
	uporabniskoime varchar NULL,
	CONSTRAINT uporabnik_pk PRIMARY KEY (id)
);
```

**Comment by nyanSpruk** [comment]
> ```sql
> CREATE TABLE public.uporabnik (
> 	id serial NOT NULL,
> 	ime varchar NULL,
> 	priimek varchar NULL,
> 	uporabniskoime varchar NULL,
> 	CONSTRAINT uporabnik_pk PRIMARY KEY (id)
> );
> ```

No need to put `NOT NULL` here because by having `SERIAL`, it automatically assigns it `NOT NULL`

**Comment by bl4ko** [comment]
Yeah you are right, the `NOT NULL` keyword was given for better redability (it obviously has no effect).

**Comment by nyanSpruk** [comment]
Database has been created on an external server, so there is no need to have local databases. We can still create local DB instances for more in depth testing. But this will do for now
IP will be sent to each person privately.

**Comment by bl4ko** [comment]
@nyanSpruk also put the credentials into [repository secrets](https://i.imgur.com/wWkaKNo.jpg), so that we can test the database with github actions and ci/cd scripts.

**Comment by nyanSpruk** [comment]
> @nyanSpruk also put the credentials into [repository secrets](https://i.imgur.com/wWkaKNo.jpg), so that we can test the database with github actions and ci/cd scripts.

Done

**Comment by bl4ko** [comment]
Closing this issue.
