### ISSUE TITLE
Implementacija knjižnice za delo z entitetami s pomočjo JDBC [6 točk]:

### ISSUE THREAD

**Issue by nyanSpruk** [nyanSpruk/PRPO-Naloge#9]
- [x] V konfiguracijsko datoteko config.yaml dodajte definicijo podatkovnega vira, ki ga bomo uporabili za dostop do podatkovne baze:

```
kumuluzee:
  name: simple-jdbc-sample
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/SimpleJdbcDS
      connection-url: jdbc:postgresql://localhost:5432/uporabniki
      username: postgres
      password: postgres
```

- [x] Dodajte še gonilnik za JDBC.

```
<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>${postgresql.version}</version>
</dependency>

```

- [x] V projektu kreirajte abstraktni razred Entiteta, ki implementira vmesnik java.io.Serializable ter ima definirano lastnost id (int). Omenjeni razred predstavlja generično entiteto (zapis v podatkovni bazi), id pa njen enolični ključ. Razred naj tudi vsebuje metodi get in set (Code -> Generate -> Getter and Setter) za nastavljanje in branje ključa.

- [x] Za tabelo uporabnik ustvarite javanski razred, ki razširja razred Entiteta ter vsebuje enaka polja kot tabela, ki ste jo izbrali. Razred mora imeti definirane ustrezne get() in set() metode.

- [x] Pri delu s podatkovno bazo bomo sledili vzorcu DAO (Data Access Object). Najprej kreirajte vmesnik (interface) BaseDao. Ta naj definira osnovne operacije nad entitetami ki omogočajo branje in pisanje v bazo:

```
Connection getConnection();

Entiteta vrni(int id);

void vstavi(Entiteta ent);

void odstrani(int id);

void posodobi(Entiteta ent);

List<Entiteta> vrniVse();
```

- [x] Nato kreirajte implementacijo vmesnika BaseDao (UporabnikDaoImpl), ki vsebuje JDBC kodo za branje, vstavljanje, spreminjanje in brisanje entitete uporabnik. Razred naj bo pripravljen po vzorcu singleton – instanca razreda naj se ustvari samo enkrat.

- [x] Pri implementaciji metode getConnection si pomagajte z naslednjo kodo, ki pridobi povezavo na podatkovno bazo:

```
InitialContext initCtx = new InitialContext();
DataSource ds = (DataSource) initCtx.lookup("jdbc/SimpleJdbcDS");
return ds.getConnection();
```

- [x] Pripravite` metodo, ki bo rezultate poizvedb po bazi pretvarjala v Java objekte.

```
private Uporabnik getUporabnikFromRS(ResultSet rs) throws SQLException {

    String ime = rs.getString("ime");
    String priimek = rs.getString("priimek");
    String uporabniskoIme = rs.getString("uporabniskoime");
    return new Uporabnik(ime, priimek, uporabniskoIme);
}
```

- [x] Za poizvedbe v bazo uporabite prepared statement. Primer:

```
@Override
public Entiteta vrni(int id) {

    PreparedStatement ps = null;

    try {

        if (con == null) {
            con = getConnection();
        }

        String sql = "SELECT * FROM uporabnik WHERE id = ?";
        ps = con.prepareStatement(sql);
        ps.setInt(1, id);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            return getUporabnikFromRS(rs);
        } else {
            log.info("Uporabnik ne obstaja");
        }

    } catch (SQLException e) {
        log.severe(e.toString());
    } finally {
        if (ps != null) {
            try {
                ps.close();
            } catch (SQLException e) {
                log.severe(e.toString());
            }
        }
    }
    return null;
}
```

- [x] V metodi get v servletu demonstrirajte delovanje vseh implementiranih metod razreda UporabnikDaoImpl.

**Comment by bl4ko** [comment]
Poglej ce lahko, da se uporabniki pravilno nastavi id, naslednja koda v `PrviJdbcServlet.java` nedela:

```java
BaseDao uporabnikDao = UporabnikDaoImpl.getInstance();
Uporabnik firstUser = new Uporabnik("Janez", "Novak", "janeznovak");
uporabnikDao.vstavi(firstUser);

// Problem v naslednji vrstici, id uporabnika se ne nastavi avtomatsko, zato naslednja funkcija vrze error
uporabnikDao.odstrani(firstUser.getId());
```

**Comment by nyanSpruk** [comment]
> @nyanSpruk vecina narejena na [branch](https://github.com/nyanSpruk/PRPO-Naloge/tree/9-implementacija-knji%C5%BEnice-za-delo-z-entitetami-s-pomo%C4%8Djo-jdbc-6-to%C4%8Dk).
> 
> Treba samo popraviti naslednjo napako:
> 
> ```java
> // PrviJdbcServlet.java
> BaseDao uporabnikDao = UporabnikDaoImpl.getInstance();
> Uporabnik firstUser = new Uporabnik("Janez", "Novak", "janeznovak");
> uporabnikDao.vstavi(firstUser);
> 
> // Problem v naslednji vrstici, id uporabnika se ne nastavi avtomatsko, zato naslednja funkcija vrze error
> uporabnikDao.odstrani(firstUser.getId());
> ```

Try something like in 
```java
UporabnikDaoImpl.vstavi()
```
After inserting the user
```java
int affectedRows = statement.executeUpdate();

if (affectedRows == 0) {
    throw new SQLException("Creating user failed, no rows affected.");
}

try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
    if (generatedKeys.next()) {
        ((Uporabnik) ent).setId(generatedKeys.getInt(1));
    }
    else {
        throw new SQLException("Creating user failed, no ID obtained.");
    }
}
```

**Comment by bl4ko** [comment]
Great works now, the following keyword (`Statement.RETURN_GENERATED_KEYS`) did the trick 😄 

```java
 ps = connection.prepareStatement(QUERY, Statement.RETURN_GENERATED_KEYS); 
```

**Comment by nyanSpruk** [comment]
Completed at #16
